apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: main
    kueue.x-k8s.io/role-hash: 9b7efa80
    kueue.x-k8s.io/workload: pod-simple-dawn-example-5dq6m-2bb03
    workflows.argoproj.io/node-id: simple-dawn-example-5dq6m
    workflows.argoproj.io/node-name: simple-dawn-example-5dq6m
    workflows.argoproj.io/pod-gc-strategy: OnPodCompletion/1m0s
  creationTimestamp: "2026-02-06T09:49:21Z"
  finalizers:
  - kueue.x-k8s.io/managed
  generation: 2
  labels:
    kueue.x-k8s.io/managed: "true"
    kueue.x-k8s.io/podset: main
    kueue.x-k8s.io/priority-class: medium
    kueue.x-k8s.io/queue-name: default-queue
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/workflow: simple-dawn-example-5dq6m
  name: simple-dawn-example-5dq6m
  namespace: mg36964-1
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: simple-dawn-example-5dq6m
    uid: 51ba2012-7f01-48be-a77b-30c8f634d785
  resourceVersion: "1668781105"
  uid: fab6f476-a771-49d7-a5ab-fa2a4dff3dbf
spec:
  containers:
  - args:
    - /argo/staging/script
    command:
    - /var/run/argo/argoexec
    - emissary
    - --loglevel
    - info
    - --log-format
    - text
    - --gloglevel
    - "0"
    - --
    - /bin/bash
    env:
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_NODE_ID
      value: simple-dawn-example-5dq6m
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: ghcr.io/jamesdoingstuff/dawn:latest
    imagePullPolicy: Always
    name: main
    resources:
      limits:
        cpu: "1"
        memory: 250Mi
      requests:
        cpu: "1"
        memory: 250Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 160196
      runAsUser: 1227486
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmpdir
    - mountPath: /var
      name: vardir
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
    workingDir: /dawn
  - command:
    - argoexec
    - wait
    - --loglevel
    - info
    - --log-format
    - text
    - --gloglevel
    - "0"
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_WORKFLOW_NAME
      value: simple-dawn-example-5dq6m
    - name: ARGO_WORKFLOW_UID
      value: 51ba2012-7f01-48be-a77b-30c8f634d785
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_NODE_ID
      value: simple-dawn-example-5dq6m
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: quay.io/argoproj/argoexec:v3.7.0
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 160196
      runAsUser: 1227486
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/secret/artifact-s3
      name: artifact-s3
      readOnly: true
    - mountPath: /mainctrfs/tmp
      name: tmpdir
    - mountPath: /mainctrfs/var
      name: vardir
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /tmp
      name: tmp-dir-argo
      subPath: "0"
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - argoexec
    - init
    - --loglevel
    - info
    - --log-format
    - text
    - --gloglevel
    - "0"
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_WORKFLOW_NAME
      value: simple-dawn-example-5dq6m
    - name: ARGO_WORKFLOW_UID
      value: 51ba2012-7f01-48be-a77b-30c8f634d785
    - name: ARGO_CONTAINER_NAME
      value: init
    - name: ARGO_TEMPLATE
      value: '{"name":"run-calibration","inputs":{},"outputs":{"artifacts":[{"name":"result","path":"/tmp/result.nxs","archive":{"none":{}}}]},"metadata":{"labels":{"kueue.x-k8s.io/priority-class":"medium","kueue.x-k8s.io/queue-name":"default-queue"}},"script":{"name":"","image":"ghcr.io/jamesdoingstuff/dawn:latest","command":["/bin/bash"],"workingDir":"/dawn","resources":{},"volumeMounts":[{"name":"tmpdir","mountPath":"/tmp"},{"name":"vardir","mountPath":"/var"}],"source":"cat
        /test_data/local_config.json\nexport _JAVA_OPTIONS=-Duser.home=/tmp/\n./dawn
        -configuration /tmp/ -consoleLog -noSplash -data @none -application uk.ac.diamond.scisoft.diffraction.powder.application.powdercalibrate
        -path /test_data/local_config.json\nfind *-dawn.log -exec cat {} +\nls -la
        /tmp/\nsleep 10m\n"},"volumes":[{"name":"vardir","emptyDir":{}}],"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"sci-nas-s3.diamond.ac.uk","bucket":"k8s-workflows-test","region":"unsupported","accessKeySecret":{"name":"artifact-s3","key":"access-key"},"secretKeySecret":{"name":"artifact-s3","key":"secret-key"},"key":"simple-dawn-example-5dq6m/simple-dawn-example-5dq6m"}}}'
    - name: ARGO_NODE_ID
      value: simple-dawn-example-5dq6m
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: quay.io/argoproj/argoexec:v3.7.0
    imagePullPolicy: IfNotPresent
    name: init
    resources:
      limits:
        cpu: "1"
        memory: 250Mi
      requests:
        cpu: "1"
        memory: 250Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 160196
      runAsUser: 1227486
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/secret/artifact-s3
      name: artifact-s3
      readOnly: true
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
  nodeName: cs05r-sc-cloud-19.diamond.ac.uk
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 160196
    runAsUser: 1227486
  serviceAccount: argo-workflow
  serviceAccountName: argo-workflow
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: var-run-argo
  - emptyDir: {}
    name: tmp-dir-argo
  - emptyDir: {}
    name: vardir
  - name: tmpdir
    persistentVolumeClaim:
      claimName: simple-dawn-example-5dq6m-tmpdir
  - name: artifact-s3
    secret:
      defaultMode: 420
      items:
      - key: access-key
        path: access-key
      - key: secret-key
        path: secret-key
      secretName: artifact-s3
  - emptyDir: {}
    name: argo-staging
  - name: kube-api-access-57dmh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T09:49:33Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T09:49:33Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T09:49:45Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T09:49:45Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T09:49:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: "1"
      ephemeral-storage: 100Mi
      memory: 250Mi
    containerID: containerd://ab0840fd3808d8ad967257d15c1aa540440c8dba699232a0e8a2ddf13a51b7ee
    image: ghcr.io/jamesdoingstuff/dawn:latest
    imageID: ghcr.io/jamesdoingstuff/dawn@sha256:8577a0e5cc20812f93620347e1d8e6bfa71638060eb7a7235a1ac7206f6dd64a
    lastState: {}
    name: main
    ready: true
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 2Gi
        memory: 250Mi
      requests:
        cpu: "1"
        ephemeral-storage: 100Mi
        memory: 250Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-02-06T09:49:44Z"
    user:
      linux:
        gid: 160196
        supplementalGroups:
        - 160196
        uid: 1227486
    volumeMounts:
    - mountPath: /tmp
      name: tmpdir
    - mountPath: /var
      name: vardir
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
      recursiveReadOnly: Disabled
  - allocatedResources:
      cpu: 500m
      ephemeral-storage: 100Mi
      memory: 2Gi
    containerID: containerd://2eb092ede74e6b3bc29296c0ccd878b584c561ccd8d13151561612a082dd3577
    image: quay.io/argoproj/argoexec:v3.7.0
    imageID: quay.io/argoproj/argoexec@sha256:075d0745ef9390117d06cb02fe620acd3a5f239590398c51fa920abffda0d4ab
    lastState: {}
    name: wait
    ready: true
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 2Gi
        memory: 4Gi
      requests:
        cpu: 500m
        ephemeral-storage: 100Mi
        memory: 2Gi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-02-06T09:49:45Z"
    user:
      linux:
        gid: 160196
        supplementalGroups:
        - 160196
        uid: 1227486
    volumeMounts:
    - mountPath: /argo/secret/artifact-s3
      name: artifact-s3
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /mainctrfs/tmp
      name: tmpdir
    - mountPath: /mainctrfs/var
      name: vardir
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /tmp
      name: tmp-dir-argo
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.101.230.60
  hostIPs:
  - ip: 10.101.230.60
  initContainerStatuses:
  - allocatedResources:
      cpu: "1"
      ephemeral-storage: 100Mi
      memory: 250Mi
    containerID: containerd://a876bde98b2a1342080d5c378a67bdffb7036c6edc735dff9cdd255c20d13e9c
    image: quay.io/argoproj/argoexec:v3.7.0
    imageID: quay.io/argoproj/argoexec@sha256:075d0745ef9390117d06cb02fe620acd3a5f239590398c51fa920abffda0d4ab
    lastState: {}
    name: init
    ready: true
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 2Gi
        memory: 250Mi
      requests:
        cpu: "1"
        ephemeral-storage: 100Mi
        memory: 250Mi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://a876bde98b2a1342080d5c378a67bdffb7036c6edc735dff9cdd255c20d13e9c
        exitCode: 0
        finishedAt: "2026-02-06T09:49:33Z"
        reason: Completed
        startedAt: "2026-02-06T09:49:32Z"
    user:
      linux:
        gid: 160196
        supplementalGroups:
        - 160196
        uid: 1227486
    volumeMounts:
    - mountPath: /argo/secret/artifact-s3
      name: artifact-s3
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-57dmh
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.38.128.4
  podIPs:
  - ip: 10.38.128.4
  qosClass: Burstable
  startTime: "2026-02-06T09:49:27Z"
