apiVersion: v1
kind: Pod
metadata:
  name: dawn
  namespace: gmg29649
spec:
  containers:
    - name: dawn
      image: ghcr.io/jamesdoingstuff/dawn:latest
      command: ["sleep", "infinity"]

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
        - name: dawn-work
          mountPath: /dawn/work

  volumes:
    - name: tmp
      emptyDir: {}
    - name: dawn-work
      emptyDir: {}
